config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      "admins/sessions",
    passwords:     "admins/paswwords",
    registrations: "admins/registrations"
  }

  devise_for :users, controllers: {
    sessions:      "users/sessions",
    passwords:     "users/passwords",
    registrations: "users/registrations"
  }

  #トップページをルートパスに指定
  root to: 'top#top'

  get 'admins/top' => 'admins#top'

  get 'admins/users/unsubscribed' => 'admins/users#unsubscribed'

  namespace :admins do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :things, only: [:index, :show, :edit, :update, :destroy]
    resources :locations, only: [:index, :show, :edit, :update, :destroy]
  end

  get 'admins/users/:id/unsubscribed_show/' => 'admins/users#unsubscribed_show', as: 'unsubscribed_show_user'
  patch 'admins/users/:id/revive' => 'admins/users#revive_account', as: 'revive_account_user'

  get 'users/clip'
  resources :users, only: [:create, :show, :edit, :update, :destroy]

  resources :things, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :locations, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :friendships, only: [:new, :create, :index, :destroy]

  resources :rooms, only: [:create, :show, :destroy]

  resources :messages, only: [:create, :edit, :update, :destroy]

  get  'inquiries/index' =>'inquiries#index'
  post 'inquiries/confirm' => 'inquiries#confirm'
  post 'inquiries/done' => 'inquiries#done'

  get 'top/guide' =>'top#guide'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/thing.rb
class Thing < ApplicationRecord
  belongs_to :user, optional: true

  attachment :thing_image

  # ラジオボタン
  enum public_status: {公開しない:1, 公開する:2}

  # バリデーション
  validates :thing_name, presence: true
  validates :thing_memo, length: { maximum: 2000 }

  # paranoia
  acts_as_paranoid
end

app/controllers/admins/things_controller.rb
class Admins::ThingsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @things = Thing.all.page(params[:page]).per(20)
  end

  def show
    @thing = Thing.with_deleted.find(params[:id])
  end

  def edit
    @thing = Thing.with_deleted.find(params[:id])
  end

  def update
    @thing = Thing.with_deleted.find(params[:id])
    if @thing.update(thing_params)
      flash[:notice] = @thing.thing_name + "を編集しました。"
      redirect_to admins_thing_path(@thing.id)
    else
      flash[:alert] = "編集できませんでした。"
      render "edit"
    end
  end

  def destroy
    thing = Thing.with_deleted.find(params[:id])
    thing.really_destroy!
    flash[:alert] = thing.thing_name + "を削除しました。"
    redirect_to admins_things_path
  end

  def thing_params
    params.require(:thing).permit(
      :thing_name,
      :thing_image,
      :thing_url,
      :thing_memo,
      :public_status,
      :user_id
    )
  end

end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :authenticate_user!

  def new
    @thing = Thing.new
  end

  def create
    @thing = Thing.new(thing_params)
    @thing.user_id = current_user.id
    if @thing.save
      flash[:notice] = "クリップ完了"
      redirect_to thing_path(@thing.id)
    else
      render "new"
    end
  end

  def show
    @thing = Thing.find(params[:id])
    @t_user = User.find_by(id: @thing.user_id)
    if current_user.is_friend?(@t_user)
    elsif current_user.id == @t_user.id
    else
      flash[:alert] = "そのページへは行けません。"
      redirect_to user_path(current_user.id)
    end
  end

  def edit
    @thing = Thing.find(params[:id])
    if current_user.id == @thing.user_id
    else
      flash[:alert] = "そのページへは行けません。"
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @thing = Thing.find(params[:id])
    if @thing.update(thing_params)
      flash[:notice] = @thing.thing_name + "を編集しました。"
      redirect_to thing_path(@thing.id)
    else
      flash[:alert] = "編集できませんでした。"
      render "edit"
    end
  end

  def destroy
    thing = Thing.find(params[:id])
    thing.really_destroy!
    flash[:alert] = thing.thing_name + "を削除しました。"
    redirect_to user_path(current_user)
  end

  private

  def thing_params
    params.require(:thing).permit(
      :thing_name,
      :thing_image,
      :thing_url,
      :thing_memo,
      :public_status,
      :user_id
    )
  end

end

app/helpers/admins/things_helper.rb
module Admins::ThingsHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/admins/things/edit.html.erb
<% if @thing.errors.any? %>
  <div id="error_explanation" class="well well-compact col-md-4 col-md-offset-4" >
    <h3><%= @thing.errors.count %>件のエラーが発生しました。</h3>
    <ul>
      <% @thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="col-xs-12 edit_thing_form">
  <div class="well well-compact col-md-6 col-md-offset-3" style="box-shadow: 4px 4px 4px 4px rgba(0,0,0,0.7); background-color: rgba( 245, 245, 245, 0.8 );">
    <%= form_for @thing, url: admins_thing_path do |f| %>
      <div class="col-md-12" style="margin-bottom: 10px; font-size: 40px; text-align: center; text-shadow: 1px 1px 1px #000000; color: #ffd700; -webkit-text-stroke: 0.2px black;">
        <strong>Edit object</strong>
      </div>
      <div class="field col-md-10 col-md-offset-1" style="margin-bottom: 30px;">
        <%= f.label :名前 %>
        <%= f.text_field :thing_name, class:"form-control" %>
      </div>
      <div class="field col-md-10 col-md-offset-1" style="margin-bottom: 30px;">
        <%= f.label :画像 %>
        <%= f.attachment_field :thing_image, placeholder: "イメージ画像を選択" %>
      </div>
      <div class="field col-md-10 col-md-offset-1" style="margin-bottom: 30px;">
        <%= f.label :関連 %><strong>URL</strong>
        <%= f.text_field :thing_url, class:"form-control"  %>
      </div>
      <div class="field col-md-10 col-md-offset-1" style="margin-bottom: 30px;">
        <%= f.label :メモ %><strong> （2000文字まで入力できます。）</strong>
        <%= f.text_area :thing_memo, class:"form-control", size:"30x6" %>
      </div>
      <div class="field col-xs-12" style="margin-bottom: 30px;">
        <div class="col-xs-6" style="text-align: center">
          <%= f.radio_button :public_status, :公開しない, checked: "checked" %>
          <%= f.label :公開しない, class: "" %>
        </div>
        <div class="col-xs-6" style="text-align: center">
          <%= f.radio_button :public_status, :公開する %>
          <%= f.label :公開する, class: "" %>
        </div>
      </div>
      <div class="actions" style="text-align: center; margin-bottom: 20px;">
        <%= f.submit '      変更を保存      ', "data-confirm" => "管理者権限で、本当に編集しますか?", class:"btn-lg btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admins/things/index.html.erb
<div class="admin_thing_index" style="margin-bottom: 20px; width: 350px; margin: 0 auto;">
  <div class="title" style="padding-bottom: 10px; font-size: 40px; text-align: center; text-shadow: 4px 4px 4px #000000; color: #ffd700; -webkit-text-stroke: 0.2px black;">
    <strong>Objects</strong>
  </div>
  <% @things.each do |thing| %>
    <div class="thing_index" style="height: 60px; margin-bottom: 20px; box-shadow: 4px 4px 4px 4px rgba(0,0,0,0.6);">
      <%= link_to admins_thing_path(thing.id), class:"" do %>
        <div class="thing_image col-xs-2" style="padding-top: 5px; padding-bottom: 5px; padding-left: 15px;">
          <%= attachment_image_tag thing, :thing_image,　format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "/images/no_image_camera_medium.jpg", size: "50x50" %>
        </div>
        <div class="thing_name col-xs-10" style="height: 60px; padding-top: 15px; padding-bottom: 15px; padding-left: 20px; float: left; font-size: 20px; color: black; text-overflow: ellipsis ; overflow: hidden; white-space: nowrap;">
          <%= thing.thing_name %>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="" style="text-align: center; width: 100%;">
    <%= paginate @things, class:"paginate" %>
  </div>
</div>


<style type="text/css">
@media screen and (max-width:768px) {
  #contents {
    padding-top: 4em;
    padding-bottom: 6em;
  }
}
</style>

app/views/admins/things/show.html.erb
<div class="thing_show row well well-compact" style="border-radius: 20px; box-shadow: 4px 4px 4px 4px rgba(0,0,0,0.7);">
  <div class="thing_name col-xs-12" style="margin-bottom: 30px; text-align: center; border-bottom: solid 3px #1c1c80;">
    <strong><%= @thing.thing_name %></strong>
  </div>
  <br>
  <br>
  <div class="thing_info">
    <div class="thing_image col-sm-5" style="padding-left: 30px; padding-bottom: 40px;">
      <%= attachment_image_tag @thing, :thing_image,　format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "/images/no_image_camera_medium.jpg", size: "250x250" %>
    </div>
    <div class="thing_detail col-sm-7" style="margin-top: 0px; margin-bottom: 10px; font-size: 16px;">
      <div class="thing_url col-xs-12" style="padding-top: 0px; word-wrap: break-word;">
        <p style="margin-bottom: 4px;"><strong>・URL</strong></p>
        <P style="margin-bottom: 20px;"><%= text_url_to_link(h(@thing.thing_url)).html_safe %></p>
      </div>
      <div class="thing_memo col-xs-12" style="">
        <p style="margin-bottom: 4px;"><strong>・メモ</strong></p>
        <% if @thing.thing_memo.blank? %>
          <p style="margin-bottom: 20px;">まだメモはありません</p>
        <% else %>
          <div class="text-area alert alert-info" style="word-wrap: break-word;">
            <%= simple_format(@thing.thing_memo) %>
          </div>
        <% end %>
      </div>
      <div class="thing_memo col-xs-12" style="">
        <% if @thing.public_status == "公開しない" %>
          <div class="thing_private" style="word-wrap: break-word;">
            <p style="margin-bottom: 4px;"><strong>・公開ステータス</strong></p>
            <p style="color: blue;"><%= @thing.public_status %></p>
          </div>
          <hr>
        <% else %>
          <div class="thing_pablic" style="word-wrap: break-word;">
            <p style="margin-bottom: 4px;"><strong>・公開ステータス</strong></p>
            <p style="color: red;"><%= @thing.public_status %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="thing_edit_delete" style="text-align: center">
  <div class='thing_edit col-xs-6' style="margin: 30px auto">
    <%= link_to edit_admins_thing_path(@thing.id), style:"box-shadow: 3px 3px 3px 3px rgba(0,0,0,0.7);", class:"btn-lg btn-success", method: :get do %>
      <span class="glyphicon glyphicon-wrench"></span> 編集 <span class="glyphicon glyphicon-wrench"></span>
    <% end %>
  </div>
  <div class='thing_delete col-xs-6' style="margin: 30px auto">
    <%= link_to admins_thing_path(@thing.id), "data-confirm" => "管理者権限で、本当に削除しますか?", style:"box-shadow: 3px 3px 3px 3px rgba(0,0,0,0.7);", class:"btn-lg btn-danger", method: :delete do %>
      <span class="glyphicon glyphicon-trash"></span> 削除 <span class="glyphicon glyphicon-trash"></span>
    <% end %>
  </div>
</div>

<% if User.find_by(id: @thing.user_id).present? %>
  <div class="thing_back" style="text-align: center">
    <div class='thing_edit col-xs-12' style="margin: 30px auto">
      <%= link_to admins_user_path(@thing.user_id), style:"box-shadow: 3px 3px 3px 3px rgba(0,0,0,0.7);", class:"btn-lg btn-default", method: :get do %>
        ユーザーページに戻る
      <% end %>
    </div>
  </div>
<% else %>
  <div class="thing_back" style="text-align: center">
    <div class='thing_back_button col-xs-12' style="margin: 30px auto">
      <%= link_to unsubscribed_show_user_path(@thing.user_id), style:"box-shadow: 3px 3px 3px 3px rgba(0,0,0,0.7);", class:"btn-lg btn-default", method: :get do %>
        ユーザーページに戻る
      <% end %>
    </div>
  </div>
<% end %>


<style type="text/css">
.thing_name {
  font-size: 40px;
}
.thing_show {
  width: 750px;
  margin: 0 auto;
}
.thing_image {
  margin-top: 10px;
  padding-right: 0px;
}

@media screen and (max-width:767px) {
  .thing_name {
    font-size: 22px;
  }
  .thing_show {
    width: 350px;
    margin: 0 auto;
  }
  .thing_image {
    margin: 0 auto;
    margin-top: 20px;
    margin-bottom: 40px;
  }
}
</style>