config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      "admins/sessions",
    passwords:     "admins/paswwords",
    registrations: "admins/registrations"
  }

  devise_for :users, controllers: {
    sessions:      "users/sessions",
    passwords:     "users/passwords",
    registrations: "users/registrations"
  }

  #トップページをルートパスに指定
  root to: 'top#top'

  get 'admins/top' => 'admins#top'

  get 'admins/users/unsubscribed' => 'admins/users#unsubscribed'

  namespace :admins do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :things, only: [:index, :show, :edit, :update, :destroy]
    resources :locations, only: [:index, :show, :edit, :update, :destroy]
  end

  get 'admins/users/:id/unsubscribed_show/' => 'admins/users#unsubscribed_show', as: 'unsubscribed_show_user'
  patch 'admins/users/:id/revive' => 'admins/users#revive_account', as: 'revive_account_user'

  get 'users/clip'
  resources :users, only: [:create, :show, :edit, :update, :destroy]

  resources :things, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :locations, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :friendships, only: [:new, :create, :index, :destroy]

  resources :rooms, only: [:create, :show, :destroy]

  resources :messages, only: [:create, :edit, :update, :destroy]

  get  'inquiries/index' =>'inquiries#index'
  post 'inquiries/confirm' => 'inquiries#confirm'
  post 'inquiries/done' => 'inquiries#done'

  get 'top/guide' =>'top#guide'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# バリデーション
  validates :admin_name, presence: true
  validates :admin_name, length: { minimum: 2 }
  validates :admin_name, length: { maximum: 10 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :room, optional: true
  belongs_to :user, optional: true

  # paranoia
  acts_as_paranoid
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  # 外部キーが複数ある場合のアソシエーション
  # friendshipテーブルのfrom_user_idカラムまたはto_user_idカラムの値と同じidの値を持つユーザーが削除されると、friendshipテーブルのレコードも削除される
  belongs_to :from_user, class_name: 'User', :foreign_key => 'from_user_id'
  belongs_to :to_user, class_name: 'User', :foreign_key => 'to_user_id'

  # paranoia
  acts_as_paranoid
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :content

  validates :name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 30 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :content, presence: true, length: { maximum: 2000 }
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user, optional: true

  attachment :location_image

  # ラジオボタン
  enum public_status: {公開しない:1, 公開する:2}

  # geocoder が address から経度・緯度を取得
  geocoded_by :address
  after_validation :geocode

  # バリデーション
  validates :location_name, presence: true
  validates :location_memo, length: { maximum: 2000 }

  # paranoia
  acts_as_paranoid

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :room, optional: true

  # バリデーション
  validates :content, length: { maximum: 1000 }

  # paranoia
  acts_as_paranoid
end

app/models/room.rb
class Room < ApplicationRecord
  # 外部キーが複数ある場合のアソシエーション
  # roomテーブルのinvite_user_idカラムまたはinvited_user_idカラムの値と同じidの値を持つユーザーが削除されると、roomテーブルのレコードも削除される
  belongs_to :invite_user, class_name: 'User', :foreign_key => 'invite_user_id'
  belongs_to :invited_user, class_name: 'User', :foreign_key => 'invited_user_id'

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  # paranoia
  acts_as_paranoid
end

app/models/thing.rb
class Thing < ApplicationRecord
  belongs_to :user, optional: true

  attachment :thing_image

  # ラジオボタン
  enum public_status: {公開しない:1, 公開する:2}

  # バリデーション
  validates :thing_name, presence: true
  validates :thing_memo, length: { maximum: 2000 }

  # paranoia
  acts_as_paranoid
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :user_image

  has_many :things, dependent: :destroy

  has_many :locations, dependent: :destroy

  # 外部キーが複数ある場合のアソシエーション
  # friendshipテーブルのfrom_user_idカラムまたはto_user_idカラムの値と同じidの値を持つユーザーを削除すると、friendshipテーブルのレコードも削除される
  has_many :from_user_transactions, class_name: 'Friendship', :foreign_key => 'from_user_id', dependent: :destroy
  has_many :to_user_transactions, class_name: 'Friendship', :foreign_key => 'to_user_id', dependent: :destroy

  # 外部キーが複数ある場合のアソシエーション
  # roomテーブルのinvite_user_idカラムまたはinvited_user_idカラムの値と同じidの値を持つユーザーを削除すると、roomテーブルのレコードも削除される
  has_many :invite_user_transactions, class_name: 'Room', :foreign_key => 'invite_user_id', dependent: :destroy
  has_many :invited_user_transactions, class_name: 'Room', :foreign_key => 'invited_user_id', dependent: :destroy

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  # バリデーション
  validates :user_name, presence: true
  validates :user_name, length: { minimum: 2 }
  validates :user_name, length: { maximum: 20 }
  validates :friend_id, presence: true, uniqueness: true
  validates :friend_id, length: { minimum: 4 }
  validates :friend_id, length: { maximum: 20 }

  # paranoia
  acts_as_paranoid


  # user(=入力したフレンドIDを持つユーザー)とすでにフレンド関係にあるかの確認
  def is_friend?(user)
    Friendship.where(from_user_id: self.id, to_user_id: user.id).exists?
  end

  # user(=ユーザーページのユーザー)との間でチャットルームが存在するかの確認
  def have_a_room?(user)
    first_friendship = Friendship.find_by(from_user_id: self.id, to_user_id: user.id)
    Room.where(friendship_id: first_friendship.id).exists?
    second_friendship = Friendship.find_by(from_user_id: user.id, to_user_id: self.id)
    Room.where(friendship_id: second_friendship.id).exists?
  end

  # user(=ユーザーページのユーザー)のIDとFriendshipのto_user_idが一致する場合に、そのFriendshipのIDを持つチャットルームが存在するかの確認
  def have_one_friendshipID_of_the_room?(user)
    one_friendship = Friendship.find_by(from_user_id: self.id, to_user_id: user.id)
    Room.where(friendship_id: one_friendship.id).exists?
  end

  # user(=ユーザーページのユーザー)のIDとFriendshipのfrom_user_idが一致する場合に、そのFriendshipのIDを持つチャットルームが存在するかの確認
  def have_another_friendshipID_of_the_room?(user)
    another_friendship = Friendship.find_by(from_user_id: user.id, to_user_id: self.id)
    Room.where(friendship_id: another_friendship.id).exists?
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def top
  end

  def guide
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "uri"
 
def text_url_to_link text
 
  URI.extract(text, ['http','https'] ).uniq.each do |url|
    sub_text = ""
    sub_text << "<a href=" << url << " target=\"_blank\">" << url << "</a>"
 
    text.gsub!(url, sub_text)
  end
 
  return text
end
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/top.html.erb
<div class="admin_top">
  <div class="admin_top_left col-md-6">
    <div class="admin_top_users col-md-10 col-md-offset-1" >
      <%= link_to admins_users_path, class:"" do %>
        <div class="users_string col-xs-12">
          Users
        </div>
      <% end %>
    </div>
  </div>
  <div class="admin_top_right col-md-6">
    <div class="admin_top_unsubscribed_users col-md-10 col-md-offset-1">
      <%= link_to admins_users_unsubscribed_path, class:"" do %>
        <div class="unsubscribed_users_string col-xs-12">
          Unsubscribed
        </div>
      <% end %>
    </div>
  </div>
  <div class="admin_bottom_left col-md-6">
    <div class="admin_top_locations col-md-10 col-md-offset-1">
      <%= link_to admins_locations_path, class:"" do %>
        <div class="location_string col-xs-12">
          locations
        </div>
      <% end %>
    </div>
  </div>
  <div class="admin_bottom_right col-md-6">
    <div class="admin_top_things col-md-10 col-md-offset-1">
      <%= link_to admins_things_path, class:"" do %>
        <div class="thing_string col-xs-12">
          Objects
        </div>
      <% end %>
    </div>
  </div>
</div>



<style type="text/css">
.admin_top {
  margin-bottom: 20px;
}

.admin_top_left {
  margin-bottom: 50px;
}
.admin_top_users {
  height: 240px;
  padding: 0px;
  opacity: 0.8;
}
.users_string {
  height: 240px;
  padding: 70px 20px 50px 20px;
  font-size: 60px;
  text-align: center;
}

.admin_top_right {
  margin-bottom: 50px;
}
.admin_top_unsubscribed_users {
  height: 240px;
  padding: 0px;
  opacity: 0.8;
}
.unsubscribed_users_string {
  height: 240px;
  padding: 80px 20px 50px 20px;
  font-size: 50px;
  text-align: center;
}

.admin_bottom_left {
  margin-bottom: 50px;
}
.admin_top_locations {
  height: 240px;
  padding: 0px;
  opacity: 0.8;
}
.location_string {
  height: 240px;
  padding: 70px 20px 50px 20px;
  font-size: 60px;
  text-align: center;
}

.admin_bottom_right {
  margin-bottom: 50px;
}
.admin_top_things {
  height: 240px;
  padding: 0px;
  opacity: 0.8;
}
.thing_string {
  height: 240px;
  padding: 70px 20px 50px 20px;
  font-size: 60px;
  text-align: center;
}



@media screen and (max-width:768px) {
  .admin_top {
    }

  .admin_top_left {
    margin-bottom: 20px;
  }
  .admin_top_users {
    height: 240px;
    padding: 0px;
    opacity: 0.8;
  }
  .users_string {
    height: 240px;
    padding: 70px 20px 50px 20px;
    font-size: 60px;
    text-align: center;
    text-shadow: 2px 2px 1px #000;
  }

  .admin_top_right {
    margin-bottom: 20px;
  }
  .admin_top_unsubscribed_users {
    height: 240px;
    padding: 0px;
    opacity: 0.8;
  }
  .unsubscribed_users_string {
    height: 240px;
    padding: 80px 10px 20px 10px;
    font-size: 50px;
    text-align: center;
    text-shadow: 2px 2px 1px #000;
  }

  .admin_bottom_left {
    margin-bottom: 20px;
  }
  .admin_top_locations {
    height: 240px;
    padding: 0px;
    opacity: 0.8;
  }
  .location_string {
    height: 240px;
    padding: 70px 20px 50px 20px;
    font-size: 60px;
    text-align: center;
    text-shadow: 2px 2px 1px #000;
  }

  .admin_bottom_right {
    margin-bottom: 20px;
  }
  .admin_top_things {
    height: 240px;
    padding: 0px;
    opacity: 0.8;
  }
  .thing_string {
    height: 240px;
    padding: 70px 20px 50px 20px;
    font-size: 60px;
    text-align: center;
    text-shadow: 2px 2px 1px #000;
  }
}

@media screen and (max-width:374px) {
  .unsubscribed_users_string {
    padding: 85px 10px 20px 10px;
    font-size: 45px;
  }


</style>