config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      "admins/sessions",
    passwords:     "admins/paswwords",
    registrations: "admins/registrations"
  }

  devise_for :users, controllers: {
    sessions:      "users/sessions",
    passwords:     "users/passwords",
    registrations: "users/registrations"
  }

  #トップページをルートパスに指定
  root to: 'top#top'

  get 'admins/top' => 'admins#top'

  get 'admins/users/unsubscribed' => 'admins/users#unsubscribed'

  namespace :admins do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :things, only: [:index, :show, :edit, :update, :destroy]
    resources :locations, only: [:index, :show, :edit, :update, :destroy]
  end

  get 'admins/users/:id/unsubscribed_show/' => 'admins/users#unsubscribed_show', as: 'unsubscribed_show_user'
  patch 'admins/users/:id/revive' => 'admins/users#revive_account', as: 'revive_account_user'

  get 'users/clip'
  resources :users, only: [:create, :show, :edit, :update, :destroy]

  resources :things, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :locations, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :friendships, only: [:new, :create, :index, :destroy]

  resources :rooms, only: [:create, :show, :destroy]

  resources :messages, only: [:create, :edit, :update, :destroy]

  get  'inquiries/index' =>'inquiries#index'
  post 'inquiries/confirm' => 'inquiries#confirm'
  post 'inquiries/done' => 'inquiries#done'

  get 'top/guide' =>'top#guide'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :user_image

  has_many :things, dependent: :destroy

  has_many :locations, dependent: :destroy

  # 外部キーが複数ある場合のアソシエーション
  # friendshipテーブルのfrom_user_idカラムまたはto_user_idカラムの値と同じidの値を持つユーザーを削除すると、friendshipテーブルのレコードも削除される
  has_many :from_user_transactions, class_name: 'Friendship', :foreign_key => 'from_user_id', dependent: :destroy
  has_many :to_user_transactions, class_name: 'Friendship', :foreign_key => 'to_user_id', dependent: :destroy

  # 外部キーが複数ある場合のアソシエーション
  # roomテーブルのinvite_user_idカラムまたはinvited_user_idカラムの値と同じidの値を持つユーザーを削除すると、roomテーブルのレコードも削除される
  has_many :invite_user_transactions, class_name: 'Room', :foreign_key => 'invite_user_id', dependent: :destroy
  has_many :invited_user_transactions, class_name: 'Room', :foreign_key => 'invited_user_id', dependent: :destroy

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  # バリデーション
  validates :user_name, presence: true
  validates :user_name, length: { minimum: 2 }
  validates :user_name, length: { maximum: 20 }
  validates :friend_id, presence: true, uniqueness: true
  validates :friend_id, length: { minimum: 4 }
  validates :friend_id, length: { maximum: 20 }

  # paranoia
  acts_as_paranoid


  # user(=入力したフレンドIDを持つユーザー)とすでにフレンド関係にあるかの確認
  def is_friend?(user)
    Friendship.where(from_user_id: self.id, to_user_id: user.id).exists?
  end

  # user(=ユーザーページのユーザー)との間でチャットルームが存在するかの確認
  def have_a_room?(user)
    first_friendship = Friendship.find_by(from_user_id: self.id, to_user_id: user.id)
    Room.where(friendship_id: first_friendship.id).exists?
    second_friendship = Friendship.find_by(from_user_id: user.id, to_user_id: self.id)
    Room.where(friendship_id: second_friendship.id).exists?
  end

  # user(=ユーザーページのユーザー)のIDとFriendshipのto_user_idが一致する場合に、そのFriendshipのIDを持つチャットルームが存在するかの確認
  def have_one_friendshipID_of_the_room?(user)
    one_friendship = Friendship.find_by(from_user_id: self.id, to_user_id: user.id)
    Room.where(friendship_id: one_friendship.id).exists?
  end

  # user(=ユーザーページのユーザー)のIDとFriendshipのfrom_user_idが一致する場合に、そのFriendshipのIDを持つチャットルームが存在するかの確認
  def have_another_friendshipID_of_the_room?(user)
    another_friendship = Friendship.find_by(from_user_id: user.id, to_user_id: self.id)
    Room.where(friendship_id: another_friendship.id).exists?
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all.page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    @thing = Thing.where(user_id: @user.id).page(params[:page]).per(20)
    @location = Location.where(user_id: @user.id).page(params[:page]).per(20)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = @user.user_name + "のアカウント情報を編集しました。"
      redirect_to admins_user_path(@user.id)
    else
      render "edit"
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:alert] = user.user_name + "のアカウント情報を削除しました。"
    redirect_to admins_users_path
  end

  def unsubscribed
    @unsubscribed_users = User.deleted.page(params[:page]).per(20)
  end

  def unsubscribed_show
    @unsubscribed_user = User.deleted.find(params[:id])
    @thing = Thing.deleted.where(user_id: @unsubscribed_user.id).page(params[:page]).per(20)
    @location = Location.deleted.where(user_id: @unsubscribed_user.id).page(params[:page]).per(20)
  end

  def revive_account
    unsubscribed_user = User.deleted.find(params[:id])
    unsubscribed_user.restore

    unsubscribed_things = Thing.deleted.where(user_id: unsubscribed_user.id)
    unsubscribed_things.each do |thing|
      thing.restore
    end

    unsubscribed_locations = Location.deleted.where(user_id: unsubscribed_user.id)
    unsubscribed_locations.each do |location|
      location.restore
    end

    unsubscribed_friendships1 = Friendship.deleted.where(to_user_id: unsubscribed_user.id)
    unsubscribed_friendships1.each do |friendship1|
      friendship1.restore
      from_user = User.deleted.find_by(id: friendship1.from_user_id)
      if from_user.present?
        friendship1.destroy
      end
    end
    unsubscribed_friendships2 = Friendship.deleted.where(from_user_id: unsubscribed_user.id)
    unsubscribed_friendships2.each do |friendship2|
      friendship2.restore
      to_user = User.deleted.find_by(id: friendship2.to_user_id)
      if to_user.present?
        friendship2.destroy
      end
    end

    unsubscribed_rooms1 = Room.deleted.where(invite_user_id: unsubscribed_user.id)
    unsubscribed_rooms1.each do |room1|
      room1.restore
      invited_user = User.deleted.find_by(id: room1.invited_user_id)
      if invited_user.present?
        room1.destroy
      else
        unsubscribed_messages = Message.deleted.where(room_id: room1.id)
        unsubscribed_messages.each do |message|
          message.restore
        end
        unsubscribed_entries = Entry.deleted.where(room_id: room1.id)
        unsubscribed_entries.each do |entry|
          entry.restore
        end
      end
    end
    unsubscribed_rooms2 = Room.deleted.where(invited_user_id: unsubscribed_user.id)
    unsubscribed_rooms2.each do |room2|
      room2.restore
      invite_user = User.deleted.find_by(id: room2.invite_user_id)
      if invite_user.present?
        room2.destroy
      else
        unsubscribed_messages = Message.deleted.where(room_id: room2.id)
        unsubscribed_messages.each do |message|
          message.restore
        end
        unsubscribed_entries = Entry.deleted.where(room_id: room2.id)
        unsubscribed_entries.each do |entry|
          entry.restore
        end
      end
    end

    flash[:notice] = unsubscribed_user.user_name + "のアカウント情報を復元しました。"
    redirect_to admins_users_path
  end

  private

  def user_params
    params.require(:user).permit(
      :user_name,
      :user_image,
      :friend_id,
      :email,
      :password,
      :deleted_at
    )
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?

  #ユーザーサインアップ後のリダイレクト先
  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :friend_id, :user_image, :email, :password, :deleted_at, :password_confirmation])
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  #ユーザーログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  #ユーザーログアウト後のリダイレクト先
  def after_sign_out_path_for(resorce)
    root_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    if current_user.is_friend?(@user)
      @thing_public = Thing.where(user_id: @user.id, public_status: 2).page(params[:page]).per(20)
      @location_public = Location.where(user_id: @user.id, public_status: 2).page(params[:page]).per(20)
      @friendship = Friendship.find_by(to_user_id: @user.id)
      @room = Room.new
      @entry = Entry.new
    elsif current_user.id == @user.id
      @thing = Thing.where(user_id: @user.id).page(params[:page]).per(20)
      @location = Location.where(user_id: @user.id).page(params[:page]).per(20)
      @entries = current_user.entries
    else
      flash[:alert] = "そのユーザーとはフレンドではないためそのページへは行けません。"
      redirect_to user_path(current_user.id)
    end
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
      flash[:alert] = "そのページへは行けません。"
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = @user.user_name + "のアカウント情報を編集しました。"
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:alert] = user.user_name + "のアカウント情報を削除しました。"
    redirect_to root_path
  end

  def clip
  end

  private

  def user_params
    params.require(:user).permit(
      :user_name,
      :user_image,
      :friend_id,
      :email,
      :password,
      :deleted_at
    )
  end

end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/edit.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation" class="well well-compact col-md-4 col-md-offset-4" >
    <h3><%= @user.errors.count %>件のエラーが発生しました。</h3>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="col-xs-12 clip_thing_form">
  <div class="well well-compact col-md-4 col-md-offset-4" style="box-shadow: 5px 5px 5px 5px rgba(0,0,0,0.7); background-color: rgba( 245, 245, 245, 0.8 );">
    <h2 style="margin-top: 10px; margin-bottom: 30px; text-align: center;">アカウント情報編集</h2>
    <%= form_for @user, url: {action: :update} do |f| %>
      <div class="field" style="margin-bottom: 20px;">
        <%= f.label :ユーザー名 %><br />
        <%= f.text_field :user_name, autofocus: true, autocomplete: "user_name", class:"form-control" %>
      </div>
      <div class="field" style="margin-bottom: 20px;">
        <%= f.label :イメージ画像 %>
        <%= f.attachment_field :user_image, placeholder: "イメージ画像を選択" %>
      </div>
      <div class="field" style="margin-bottom: 20px;">
        <%= f.label :フレンド %><strong>ID</strong><br />
        <%= f.text_field :friend_id, autofocus: true, autocomplete: "friend_id", class:"form-control" %>
      </div>
      <div class="field" style="margin-bottom: 20px;">
        <%= f.label :Eメールアドレス %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control" %>
      </div>
      <div class="actions" style="margin-bottom: 60px;">
        <%= f.submit "変更を保存", "data-confirm" => "管理者権限で、本当に編集しますか?", class:"btn btn-success col-xs-12" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admins/users/index.html.erb
<div class="admin_user_index" style="margin-bottom: 20px; width: 350px; margin: 0 auto;">
  <div class="title" style="padding-bottom: 10px; font-size: 40px; text-align: center; text-shadow: 4px 4px 4px #000000; color: #98fb98; -webkit-text-stroke: 0.2px black;">
    <strong>Users</strong>
  </div>
  <% @users.each do |user| %>
    <div class="user_index" style="height: 60px; margin-bottom: 20px; box-shadow: 4px 4px 4px 4px rgba(0,0,0,0.6);">
      <%= link_to admins_user_path(user.id), class:"" do %>
        <div class="user_image col-xs-2" style="padding-top: 5px; padding-bottom: 5px; padding-left: 15px;">
          <%= attachment_image_tag user, :user_image,　format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "/images/no_image.jpg", size: "50x50" %>
        </div>
        <div class="user_name col-xs-10" style="height: 60px; padding-top: 15px; padding-bottom: 15px; padding-left: 20px; float: left; font-size: 20px; color: black; text-overflow: ellipsis ; overflow: hidden; white-space: nowrap;">
          <%= user.user_name %>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="" style="text-align: center; width: 100%;">
    <%= paginate @users, class:"paginate" %>
  </div>
</div>


<style type="text/css">
@media screen and (max-width:768px) {
  #contents {
    padding-top: 4em;
    padding-bottom: 6em;
  }
}
</style>

app/views/admins/users/show.html.erb
<div class='user_show' style="padding: 0px;">
  <div class="user_profile row well well-compact" style="padding: 5px 19px 0px 19px; border-radius: 20px; box-shadow: 3px 3px 3px 3px rgba(0,0,0,0.7); margin: 0 auto; margin-bottom: 30px;">
    <div class="user_image col-sm-3" style="margin-top: 40px;">
      <div class="col-xs-12" style="padding-left: 0px;">
        <%= attachment_image_tag @user, :user_image,　format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "/images/no_image.jpg", size: "150x150", style:"margin-bottom: 40px;" %>
      </div>
    </div>
    <div class="user_detail col-sm-6" style="margin-top: 20px; font-size: 16px;">
      <div class="user_name col-xs-12" style="">
        <p style="margin-bottom: 4px;"><strong>・ユーザー名</strong></p>
        <p style="margin-bottom: 20px;"><%= @user.user_name %></p>
      </div>
      <div class="email col-xs-12" style="">
        <p style="margin-bottom: 4px;"><strong>・Eメールアドレス</strong></p>
        <p style="margin-bottom: 20px;"><%= @user.email %></p>
      </div>
      <div class="friend_id col-xs-12" style="">
        <p style="margin-bottom: 4px;"><strong>・フレンドID</strong></p>
        <p style="margin-bottom: 20px;"><%= @user.friend_id %></p>
      </div>
    </div>

    <div class="col-sm-3" style="text-align: center">
      <div class='user_edit col-xs-12' style="padding: 10px; margin-top: 10px;">
        <%= link_to edit_admins_user_path(@user.id), class:"btn btn-success", method: :get do %>
          アカウント編集
        <% end %>
      </div>
      <br>
      <div class='user_delete col-xs-12' style="padding: 10px; margin-bottom: 10px;">
        <%= link_to admins_user_path(@user.id), "data-confirm" => "管理者権限で、本当に削除しますか?", class:"btn btn-danger", method: :delete do %>
          アカウント削除
        <% end %>
      </div>
    </div>
  </div>

  <div class="location_and_thing_all row" style="margin: 0 auto;" >
    <div class="col-xs-12" style="padding: 0px;">
      <div class="location_and_thing">
        <div class="left col-sm-6" style="padding: 0px;">
          <div class="user_location_index" style="margin-bottom: 20px; width: 350px; margin: 0 auto;">
            <div class="thing_title" style="padding-bottom: 10px; font-size: 40px; text-align: center; text-shadow: 4px 4px 4px #000000; color: #00bfff; -webkit-text-stroke: 0.2px black;">
              <strong>Locations</strong>
            </div>
            <% @location.each do |location| %>
              <% if location.public_status == "公開する" %>
                <div class="user_location" style="height: 60px; margin-bottom: 20px; box-shadow: 3px 3px 3px 3px rgba(0,0,0,0.6);">
                  <%= link_to admins_location_path(location.id), class:"" do %>
                    <div class="location_image col-xs-2" style="padding-top: 5px; padding-bottom: 5px; padding-left: 15px;">
                      <%= attachment_image_tag location, :location_image,　format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image_camera_medium.jpg", size: "50x50" %>
                    </div>
                    <div class="location_name col-xs-8" style="height: 60px; padding-top: 15px; padding-bottom: 15px; padding-left: 20px; float: left; font-size: 20px; color: black; text-overflow: ellipsis ; overflow: hidden; white-space: nowrap;">
                      <%= location.location_name %>
                    </div>
                    <div class="location_status col-xs-2" style="height: 60px; padding-top: 18px; padding-bottom: 18px; padding-left: 0px; font-size: 16px; color: black;">
                      <span style="background-color: red; color: white; border-radius: 5px;">OPEN</span>
                    </div>
                  <% end %>
                </div>
              <% else %>
                <div class="user_location" style="height: 60px; margin-bottom: 20px; box-shadow: 3px 3px 3px 3px rgba(0,0,0,0.6);">
                  <%= link_to admins_location_path(location.id), class:"" do %>
                    <div class="location_image col-xs-2" style="padding-top: 5px; padding-bottom: 5px; padding-left: 15px;">
                      <%= attachment_image_tag location, :location_image,　format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image_camera_medium.jpg", size: "50x50" %>
                    </div>
                    <div class="location_name col-xs-10" style="height: 60px; padding-top: 15px; padding-bottom: 15px; padding-left: 20px; float: left; font-size: 20px; color: black; text-overflow: ellipsis ; overflow: hidden; white-space: nowrap;">
                      <%= location.location_name %>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
            <div class="" style="text-align: center; width: 100%;">
              <%= paginate @location, class:"paginate" %>
            </div>
          </div>
        </div>
        <div class="right col-sm-6" style="padding: 0px;">
          <div class="user_thing_index" style="margin-bottom: 20px; width: 350px; margin: 0 auto;">
            <div class="thing_title" style="padding-bottom: 10px; font-size: 40px; text-align: center; text-shadow: 4px 4px 4px #000000; color: #ffd700; -webkit-text-stroke: 0.2px black;">
              <strong>Objects</strong>
            </div>
            <% @thing.each do |thing| %>
              <% if thing.public_status == "公開する" %>
                <div class="user_thing" style="height: 60px; margin-bottom: 20px; box-shadow: 3px 3px 3px 3px rgba(0,0,0,0.6);">
                  <%= link_to admins_thing_path(thing.id), class:"" do %>
                    <div class="thing_image col-xs-2" style="padding-top: 5px; padding-bottom: 5px; padding-left: 15px;">
                      <%= attachment_image_tag thing, :thing_image,　format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image_camera_medium.jpg", size: "50x50" %>
                    </div>
                    <div class="thing_name col-xs-8" style="height: 60px; padding-top: 15px; padding-bottom: 15px; padding-left: 20px; float: left; font-size: 20px; color: black; text-overflow: ellipsis ; overflow: hidden; white-space: nowrap;">
                      <%= thing.thing_name %>
                    </div>
                    <div class="thing_status col-xs-2" style="height: 60px; padding-top: 18px; padding-bottom: 18px; padding-left: 0px; font-size: 16px; color: black;">
                      <span style="background-color: red; color: white; border-radius: 5px;">OPEN</span>
                    </div>
                  <% end %>
                </div>
              <% else %>
                <div class="user_thing" style="height: 60px; margin-bottom: 20px; box-shadow: 3px 3px 3px 3px rgba(0,0,0,0.6);">
                  <%= link_to admins_thing_path(thing.id), class:"" do %>
                    <div class="thing_image col-xs-2" style="padding-top: 5px; padding-bottom: 5px; padding-left: 15px;">
                      <%= attachment_image_tag thing, :thing_image,　format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image_camera_medium.jpg", size: "50x50" %>
                    </div>
                    <div class="thing_name col-xs-10" style="height: 60px; padding-top: 15px; padding-bottom: 15px; padding-left: 20px; float: left; font-size: 20px; color: black; text-overflow: ellipsis ; overflow: hidden; white-space: nowrap;">
                      <%= thing.thing_name %>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
            <div class="" style="text-align: center; width: 100%;">
              <%= paginate @thing, class:"paginate" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<style type="text/css">
.user_profile {
  width: 700px;
}

@media screen and (max-width:767px) {
  .user_profile {
    width: 350px;
  }
  .user_image {
    margin-left: 33px;
    margin-bottom: 20px;
  }
  .chat_button {
    margin-top: 0px;
  }
  .friend_delete {
    margin-left: 65px;
  }
}

@media screen and (max-width:375px) {
  .location_and_thing_all {
    width: 350px;
    margin: 0 auto;
  }
}

</style>

app/views/admins/users/unsubscribed.html.erb
<div class="admin_user_index" style="margin-bottom: 20px; width: 350px; margin: 0 auto;">
  <div class="title" style="padding-bottom: 10px; font-size: 40px; text-align: center; text-shadow: 4px 4px 4px #000000; color: #ff6347; -webkit-text-stroke: 0.2px black;">
    <strong>Unsubscribed</strong>
  </div>
  <% @unsubscribed_users.each do |user| %>
    <div class="unsubscribed_index" style="height: 60px; margin-bottom: 20px; box-shadow: 4px 4px 4px 4px rgba(0,0,0,0.6);">
      <%= link_to unsubscribed_show_user_path(user.id), class:"" do %>
        <div class="user_image col-xs-2" style="padding-top: 5px; padding-bottom: 5px; padding-left: 15px;">
          <%= attachment_image_tag user, :user_image,　format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "/images/no_image.jpg", size: "50x50" %>
        </div>
        <div class="user_name col-xs-10" style="height: 60px; padding-top: 15px; padding-bottom: 15px; padding-left: 20px; float: left; font-size: 20px; color: black; text-overflow: ellipsis ; overflow: hidden; white-space: nowrap;">
          <%= user.user_name %>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="" style="text-align: center; width: 100%;">
    <%= paginate @unsubscribed_users, class:"paginate" %>
  </div>
</div>


<style type="text/css">
@media screen and (max-width:768px) {
  #contents {
    padding-top: 4em;
    padding-bottom: 6em;
  }
}
</style>