config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      "admins/sessions",
    passwords:     "admins/paswwords",
    registrations: "admins/registrations"
  }

  devise_for :users, controllers: {
    sessions:      "users/sessions",
    passwords:     "users/passwords",
    registrations: "users/registrations"
  }

  #トップページをルートパスに指定
  root to: 'top#top'

  get 'admins/top' => 'admins#top'

  get 'admins/users/unsubscribed' => 'admins/users#unsubscribed'

  namespace :admins do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :things, only: [:index, :show, :edit, :update, :destroy]
    resources :locations, only: [:index, :show, :edit, :update, :destroy]
  end

  get 'admins/users/:id/unsubscribed_show/' => 'admins/users#unsubscribed_show', as: 'unsubscribed_show_user'
  patch 'admins/users/:id/revive' => 'admins/users#revive_account', as: 'revive_account_user'

  get 'users/clip'
  resources :users, only: [:create, :show, :edit, :update, :destroy]

  resources :things, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :locations, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :friendships, only: [:new, :create, :index, :destroy]

  resources :rooms, only: [:create, :show, :destroy]

  resources :messages, only: [:create, :edit, :update, :destroy]

  get  'inquiries/index' =>'inquiries#index'
  post 'inquiries/confirm' => 'inquiries#confirm'
  post 'inquiries/done' => 'inquiries#done'

  get 'top/guide' =>'top#guide'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  # 外部キーが複数ある場合のアソシエーション
  # roomテーブルのinvite_user_idカラムまたはinvited_user_idカラムの値と同じidの値を持つユーザーが削除されると、roomテーブルのレコードも削除される
  belongs_to :invite_user, class_name: 'User', :foreign_key => 'invite_user_id'
  belongs_to :invited_user, class_name: 'User', :foreign_key => 'invited_user_id'

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  # paranoia
  acts_as_paranoid
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def show
    @room = Room.find(params[:id])
    @friendship = Friendship.where(from_user_id: current_user.id)

    @room_invite_user_c = Room.where(invite_user_id: current_user.id)
    @room_invited_user_c = Room.where(invited_user_id: current_user.id)

    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages.order(created_at: :desc).page(params[:page]).per(20)
      @message = Message.new
      @entries = @room.entries
    else
      @user = User.find_by(id: current_user.id)
      redirect_to user_path(@user.id)
      flash[:alert] = "そのページへは行けません"
    end
  end

  def create
    room = Room.new(room_params)
    entry = Entry.new(entry_params)
    user = User.find_by(id: entry.user_id)
    if current_user.have_one_friendshipID_of_the_room?(user)
      one_friendship = Friendship.find_by(from_user_id: current_user.id, to_user_id: user.id)
      one_room = Room.find_by(friendship_id: one_friendship.id)
      redirect_to room_path(one_room.id)
    elsif current_user.have_another_friendshipID_of_the_room?(user)
      another_friendship = Friendship.find_by(from_user_id: user.id, to_user_id: current_user.id)
      another_room = Room.find_by(friendship_id: another_friendship.id)
      redirect_to room_path(another_room.id)
    else
      room.save
      entry1 = Entry.create(:room_id => room.id, :user_id => current_user.id)
      entry2 = Entry.create(:room_id => room.id, :user_id => entry.user_id)
      redirect_to room_path(room.id)
      flash[:notice] = "チャットルームを作成しました！"
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.really_destroy!
    flash[:alert] = "チャットルームを削除しました"
    redirect_to user_path(current_user)
  end

  private

  def room_params
    params.require(:room).permit(:friendship_id, :invite_user_id, :invited_user_id)
  end

  def entry_params
    params.require(:entry).permit(:room_id, :user_id)
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/show.html.erb
<% if @message.errors.any? %>
  <div id="error_explanation" class="well well-compact col-md-4 col-md-offset-4" >
    <h3><%= @message.errors.count %>件のエラーが発生しました。</h3>
    <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class='room_show col-xs-12' style="margin-top: 0px;">
<!-- 左側 -->
<div class="row" style="">
  <div class="chat_list" style="margin-top: 0px;">
    <div class="title col-xs-12" style="padding: 0px;">
      <p style="margin-bottom: 3px; font-size: 30px; text-align: center; color: black; text-shadow: 3px 3px 3px #000000; color: #d2b48c; -webkit-text-stroke: 0.2px black;">
        <strong>Chat list</strong>
      </p>
    </div>
    <div class="scr chat_index well" style="margin-bottom: 20px; background-color: #ffd0cc; border-radius: 10px; box-shadow: 3px 3px 3px 3px rgba(0,0,0,0.7); background-color: rgba( 210, 180, 140, 0.8 )">
      <% @room_invite_user_c.each do |room| %>
        <% invited_user = User.find(room.invited_user_id) %>
        <% if @room.invited_user_id == room.invited_user_id %>
          <div class="user_friend" style="height: 60px; margin-bottom: 10px; background-color: #b3d9ff;">
            <%= link_to room_path(room.id) do %>
              <div class="friend_image col-xs-2" style="padding-top: 5px; padding-bottom: 5px; padding-left: 15px;">
                <%= attachment_image_tag invited_user, :user_image,　format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "/images/no_image.jpg", size: "50x50" %>
              </div>
              <div class="friend_name col-xs-10" style="height: 60px; padding-top: 18px; padding-bottom: 15px; padding-left: 30px; font-size: 18px; color: blue; text-overflow: ellipsis ; overflow: hidden; white-space: nowrap;">
                <span class="glyphicon glyphicon-user"></span> <%= invited_user.user_name %>
              </div>
            <% end %>
          </div>
        <% else %>
          <div class="user_friend" style="height: 60px; margin-bottom: 10px;">
            <%= link_to room_path(room.id) do %>
              <div class="friend_image col-xs-2" style="padding-top: 5px; padding-bottom: 5px; padding-left: 15px;">
                <%= attachment_image_tag invited_user, :user_image,　format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "/images/no_image.jpg", size: "50x50" %>
              </div>
              <div class="friend_name col-xs-10" style="height: 60px; padding-top: 18px; padding-bottom: 15px; padding-left: 30px; font-size: 18px; color: black; text-overflow: ellipsis ; overflow: hidden; white-space: nowrap;">
                <%= invited_user.user_name %>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
      <% @room_invited_user_c.each do |room| %>
        <% invite_user = User.find(room.invite_user_id) %>
        <% if @room.invite_user_id == room.invite_user_id %>
          <div class="user_friend" style="height: 60px; margin-bottom: 10px; background-color: #b3d9ff;">
            <%= link_to room_path(room.id) do %>
              <div class="friend_image col-xs-2" style="padding-top: 5px; padding-bottom: 5px; padding-left: 15px;">
                <%= attachment_image_tag invite_user, :user_image,　format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "/images/no_image.jpg", size: "50x50" %>
              </div>
              <div class="friend_name col-xs-10" style="height: 60px; padding-top: 18px; padding-bottom: 15px; padding-left: 30px; font-size: 18px; color: blue; text-overflow: ellipsis ; overflow: hidden; white-space: nowrap;">
                <span class="glyphicon glyphicon-user"></span> <%= invite_user.user_name %>
              </div>
            <% end %>
          </div>
        <% else %>
          <div class="user_friend" style="height: 60px; margin-bottom: 10px;">
            <%= link_to room_path(room.id) do %>
              <div class="friend_image col-xs-2" style="padding-top: 5px; padding-bottom: 5px; padding-left: 15px;">
                <%= attachment_image_tag invite_user, :user_image,　format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "/images/no_image.jpg", size: "50x50" %>
              </div>
              <div class="friend_name col-xs-10" style="height: 60px; padding-top: 18px; padding-bottom: 15px; padding-left: 30px; font-size: 18px; color: black; text-overflow: ellipsis ; overflow: hidden; white-space: nowrap;">
                <%= invite_user.user_name %>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="chat_user">
      <div class="chat_partner col-xs-12" style="padding: 0px;">
        <p style="margin-bottom: 3px; font-size: 30px; text-align: center; color: black; text-shadow: 3px 3px 3px #000000; color: #b3d9ff; -webkit-text-stroke: 0.2px black;">
          <strong>Chat partner</strong>
        </p>
      </div>
      <% invited_user = User.find(@room.invited_user_id) %>
      <% invite_user = User.find(@room.invite_user_id) %>
      <% if @room.invited_user_id == current_user.id %>
        <div class="user_friend col-xs-12" style="height: 60px; margin-bottom: 5px; background-color: #b3d9ff; box-shadow: 3px 3px 3px 3px rgba(0,0,0,0.7);">
          <%= link_to user_path(invite_user.id), class:"" do %>
            <div class="friend_image col-xs-2" style="padding-top: 5px; padding-bottom: 5px; padding-left: 5px;">
              <%= attachment_image_tag invite_user, :user_image,　format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "/images/no_image.jpg", size: "50x50" %>
            </div>
            <div class="friend_name col-xs-10" style="height: 60px; padding-top: 17px; padding-bottom: 15px; padding-left: 15px; font-size: 20px; color: blue; text-overflow: ellipsis ; overflow: hidden; white-space: nowrap;">
              <span class="glyphicon glyphicon-user"></span> <%= invite_user.user_name %>
            </div>
          <% end %>
        </div>
      <% elsif @room.invite_user_id == current_user.id %>
        <div class="user_friend col-xs-12" style="height: 60px; margin-bottom: 5px; background-color: #b3d9ff; box-shadow: 3px 3px 3px 3px rgba(0,0,0,0.7);">
          <%= link_to user_path(invited_user.id), class:"" do %>
            <div class="friend_image col-xs-2" style="padding-top: 5px; padding-bottom: 5px; padding-left: 5px;">
              <%= attachment_image_tag invited_user, :user_image,　format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "/images/no_image.jpg", size: "50x50" %>
            </div>
            <div class="friend_name col-xs-10" style="height: 60px; padding-top: 17px; padding-bottom: 15px; padding-left: 15px; font-size: 20px; color: blue; text-overflow: ellipsis ; overflow: hidden; white-space: nowrap;">
              <span class="glyphicon glyphicon-user"></span> <%= invited_user.user_name %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="chat_form col-xs-12" style="padding: 0px;">
      <%= form_for @message do |f| %>
      <div style="box-shadow: 3px 3px 3px 3px rgba(0,0,0,0.7);">
        <%= f.text_area :content, class:"form-control", size:"30x4", placeholder:"メッセージを入力して下さい" %>
        <%= f.hidden_field :room_id, value: @room.id %>
      </div>
        <div class="text-buttom">
          <input type="submit" name="commit" value="メッセージを投稿する" class="btn btn-primary col-xs-12" data-disable-with="投稿する" style="box-shadow: 3px 3px 3px 3px rgba(0,0,0,0.7); margin-top: 0px">
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- /左側 -->

<!-- 右側 -->
<div class="row">
  <div class="col-md-5">
  </div>
  <div class="col-md-7" style="">
    <div class="chat_message" style="">
      <% if @messages.present? %>
        <% @messages.each do |m| %>
          <% if m.user_id == current_user.id %>
            <h4 class="text-left">
              <div class="text-area alert alert-warning col-xs-12 clearfix" style="word-wrap: break-word; padding: 5px; box-shadow: 3px 3px 3px 3px rgba(0,0,0,0.7); margin-bottom: 10px;">
                <div class="chat_left" style="">
                  <div class="user_image" style="">
                    <%= attachment_image_tag m.user, :user_image,　format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "/images/no_image.jpg", size: "50x50" %>
                  </div>
                </div>
                <div class="chat_right" style="">
                  <div class="" style="">
                    <small><strong style="color: orange;"><%= m.user.user_name %></strong></small>
                  </div>
                  <div class="content" style="margin-top: 5px;">
                    <small style="line-height: 18px; color: #000000;"><%= simple_format(m.content) %></small>
                  </div>
                  <div class="" style="float: right;">
                    <small>
                      <span><%= link_to edit_message_path(m.id), class:"message_#{m.id}" do %>編集<% end %></span>
                      <span style="margin-right: 8px;"><%= link_to message_path(m.id), "data-confirm" => "このメッセージを削除しますか?", method: :delete, class:"delete_message_#{m.id}" do %>削除<% end %></span>
                      <span style="font-size: 15px;"><%= m.created_at.strftime("%Y-%m-%d  %H:%M") %></span>
                    </small>
                  </div>
                </div>
              </div>
            </h4>
          <% else %>
            <h4 class="text-left">
              <div class="text-area alert alert-info col-xs-12 clearfix" style="word-wrap: break-word; padding: 5px; box-shadow: 3px 3px 3px 3px rgba(0,0,0,0.7); margin-bottom: 10px;">
                <div class="chat_left" style="">
                  <div class="user_image" style="">
                    <%= attachment_image_tag m.user, :user_image,　format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "/images/no_image.jpg", size: "50x50" %>
                  </div>
                </div>
                <div class="chat_right" style="">
                  <div class="content" style="">
                    <small><strong style="color: blue;"><%= m.user.user_name %></strong></small>
                  </div>
                  <div class="content" style="margin-top: 5px;">
                    <small style="line-height: 18px; color: #000000;"><%= simple_format(m.content) %></small>
                  </div>
                  <div class="" style="float: right;">
                    <small>
                      <span style="font-size: 15px;"><%= m.created_at.strftime("%Y-%m-%d  %H:%M") %></span>
                    </small>
                  </div>
                </div>
              </div>
            </h4>
          <% end %>
        <% end %>
      <% else %>
        <br>
        <h3 class="text-center">メッセージはまだありません</h3>
        <br>
      <% end %>
    </div>
    <div class="" style="text-align: center; width: 100%;">
      <%= paginate @messages, class:"paginate" %>
    </div>

  </div>
</div>
<!-- /右側 -->
</div>


<style type="text/css">
/* 固定 */
.chat_list {
  position: fixed;
  top: 60px;
  left: 120px;
  width: 400px;
}
/* スクロール */
div.scr{
  width: 100%;
  height: 280px;
  overflow: scroll;
}
.chat_left {
  width: 10%;
  float: left;
}
.chat_right {
  width: 90%;
  float: left;
}

@media screen and (max-width:1300px) {
  .chat_list {
    position: fixed;
    top: 60px;
    left: 90px;
  }
}


@media screen and (max-width:1200px) {
  .chat_list {
    position: fixed;
    top: 60px;
    left: 55px;
  }
  .chat_left {
    width: 12%;
    float: left;
  }
  .chat_right {
    width: 88%;
    float: left;
  }
}

@media screen and (max-width:1050px) {
  .chat_list {
    left: 20px;
  }
}

@media screen and (max-width:990px) {
  .chat_list {
    position: static;
    margin: 0 auto;
  }
  .chat_left {
    width: 10%;
    float: left;
  }
  .chat_right {
    width: 90%;
    float: left;
  }
  #contents {
    padding-top: 4em;
    padding-bottom: 6em; /* フッタの高さ分だけ余白を設ける */
  }
}

@media screen and (max-width:600px) {
  .chat_left {
    width: 12%;
    float: left;
  }
  .chat_right {
    width: 88%;
    float: left;
  }
}

@media screen and (max-width:520px) {
  .chat_left {
    width: 14%;
    float: left;
  }
  .chat_right {
    width: 86%;
    float: left;
  }
}

@media screen and (max-width:480px) {
  .chat_left {
    width: 16%;
    float: left;
  }
  .chat_right {
    width: 84%;
    float: left;
  }
}

@media screen and (max-width:440px) {
  .chat_left {
    width: 18%;
    float: left;
  }
  .chat_right {
    width: 82%;
    float: left;
  }
}

@media screen and (max-width:420px) {
  .chat_list {
    padding: 0px;
    width: 380px;
  }
}

@media screen and (max-width:400px) {
  .chat_list {
    padding: 0px;
    width: 350px;
  }
}

</style>